FROM golang:1.26.2 AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main .


FROM debian:bookworm-slim AS slim

WORKDIR /app
COPY --from=build /app/main.bin .

RUN chmod +x ./main

EXPOSE 8080

CMD ["./main.exe"]
