name: Deployment

on:
  push:
    branches: ["main"]
jobs:

  build:
    runs-on: ubuntu-latest
    environment: NEXUS
    steps:
    - uses: actions/checkout@v4
    
    # - name: Set up Go
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: '1.26.2'

    - name: Configure insecure registry
      run: |
        echo '{"insecure-registries":["${{ secrets.NEXUS_HOST }}:${{ secrets.NEXUS_PORT }}"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Login Nexus from docker
      uses: docker/login-action@v4
      with:
          registry: ${{ secrets.NEXUS_HOST }}:${{ secrets.NEXUS_PORT }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile.dev
        push: true
        tags: ${{ secrets.NEXUS_HOST }}:${{ secrets.NEXUS_PORT }}/api-golang:${{ github.sha }}
